repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1-1
    hooks:
      - id: trailing-whitespace
        language_version: python3.7
      - id: end-of-file-fixer
        language_version: python3.7
      - id: autopep8-wrapper
        language_version: python3.7
      - id: check-yaml
        language_version: python3.7
      - id: debug-statements
        language_version: python3.7
      - id: name-tests-test
        language_version: python3.7
      - id: check-added-large-files
        language_version: python3.7
      - id: check-byte-order-marker
        language_version: python3.7
      - id: flake8
        language_version: python3.7
      - id: requirements-txt-fixer
        language_version: python3.7
      - id: detect-private-key
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-pylint
    sha: v2.1.1
    hooks:
      - id: pylint
  - repo: https://github.com/asottile/reorder_python_imports
    sha: v1.1.0
    hooks:
      - id: reorder-python-imports
